export const TRAER_TODAS = 'tareas_traer_todas'
export const CARGANDO = 'usuario_cargando'
export const ERROR = 'usuario_error'
export const CAMBIO_USUARIO_ID = 'cambio_usuario_id'
export const CAMBIO_TITULO = 'cambio_titulo'
export const GUARDAR = 'guardar'
export const ACTUALIZAR = 'tareas_actualizar'
export const LIMPIAR = 'tareas_limpiar'